require: rubocop-rails

AllCops:
  Exclude:
    - bin/**/*
    - db/schema.rb
    - node_modules/**/*
    - tmp/**/*

Metrics/AbcSize:
  Exclude:
    - db/**/*.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb
    - db/**/*.rb

Metrics/MethodLength:
  Exclude:
    - db/**/*.rb

Style/MixinUsage:
  Exclude:
    - bin/*

Naming/MemoizedInstanceVariableName:
  Enabled: true
  EnforcedStyleForLeadingUnderscores: required

Style/Documentation:
  Enabled: false

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: false

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

Rails/FilePath:
  Enabled: false
